version: '3.9'

services:
  mysql-development-user:
    image: mysql:8.0.32
    networks:
      - nwt_network
    environment:
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'nwt_project_base'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "33066:3306"

  mysql-development-product:
    image: mysql:8.0.32
    networks:
      - nwt_network
    environment:
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'shop'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "33067:3306"

  mysql-development-order:
    image: mysql:8.0.32
    networks:
      - nwt_network
    environment:
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'nwtbaza'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "33068:3306"

  nwt_project_user:
    image: "nwt_project_user"
    container_name: nwt_project_user
    restart: on-failure
    networks:
      - nwt_network
    build:
      dockerfile: Dockerfile
      context: ./nwt_user
    depends_on:
      - eureka
      - nwt_api_gateway
      - mysql-development-user
      - rabbitmq
    ports:
      - "8081:8081"

  nwt_central_config:
    image: "nwt_central_config"
    container_name: nwt_central_config
    networks:
      - nwt_network
    build:
      dockerfile: Dockerfile
      context: ./nwt_central_config
    depends_on:
      - eureka
    ports:
      - "8888:8888"

  nwt_project_order:
    image: "nwt_project_order"
    container_name: nwt_project_order
    restart: on-failure
    networks:
      - nwt_network
    build:
      dockerfile: Dockerfile
      context: ./nwt_order
    depends_on:
      - eureka
      - nwt_api_gateway
      - mysql-development-order
    ports:
      - "8083:8083"

  nwt_project_product:
    image: "nwt_project_product"
    container_name: nwt_project_product
    restart: on-failure
    networks:
      - nwt_network
    build:
      dockerfile: Dockerfile
      context: ./nwt_product
    depends_on:
      - eureka
      - nwt_api_gateway
      - mysql-development-product
      - rabbitmq
    ports:
      - "8082:8082"

  eureka:
    image: "eureka"
    container_name: eureka
    build:
      dockerfile: Dockerfile
      context: ./nwt_eureka
    networks:
      - nwt_network
    ports:
      - "8761:8761"

  nwt_api_gateway:
    image: "nwt_api_gateway"
    container_name: nwt_api_gateway
    build:
      dockerfile: Dockerfile
      context: ./nwt_api_gateway
    networks:
      - nwt_network
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - nwt_network
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  nwt_network:
    external: true
