version: '3'

services:
  mysql-development:
    image: mysql:8.0.32
    environment:
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'nwt_project_base'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "33066:3306"

  rmq:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15671:15671"