spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: nwtProjekatUser
          uri: lb://NWTPROJEKATUSER
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: productService
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/product/**
          filters:
            - AuthenticationFilter
        - id: orderService
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/order/**
          filters:
            - AuthenticationFilter