version: '3'

services:
  mysql-development:
    image: mysql:8.0.32
    environment:
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'nwtbaza'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "33068:3306"